name: pr-lint-and-test
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer Downloads
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Installing dependencies
        run: composer install

      - name: Creating perry initial files
        run: php ./bin/perry

      - name: Running phpunit tests
        run: php ./vendor/bin/phpunit

      - name: Running perry unit tests and generating documentation
        run: php ./bin/perry
